environment:
  nodejs_version: "18"

branches:
  only:
    - master 
    - main

cache: node_modules  # кеширование

install:
  - npm install --legacy-peer-deps  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования